#:schema node_modules/wrangler/config-schema.json
name = "cloudfare-telegram-template"
main = "src/index.ts"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat_v2"]

[observability]
enabled = true

[vars]
# Do not commit real values to version control.
TELEGRAM_BOT_TOKEN = "7941876106:AAE6kMLKN_DrqjWvWWaGePYNIGgIgAyYkaM"
TELEGRAM_CHAT_ID = "1722850637"
HELIUS_API_KEY = "f4a69082-8290-4b8a-9d04-7e3470958952"
AUTH_TOKEN = "17g6eF6Jl4z7lSBRRc09eQSdu6kLGRm0EUJIs2DEtoI="